language: r
warnings_are_errors: true
sudo: false
cache: packages


matrix:
  include:
    - os: linux
      dist: precise
      sudo: false
    - os: linux
      dist: trusty
      env: R_CODECOV=true
    - os: osx
      osx_image: xcode8
      brew_packages: poppler
      latex: false
    - os: osx
      osx_image: beta-xcode6.2
      disable_homebrew: true
      latex: false

cran: https://cran.rstudio.com/
r_packages: 
   - covr
   
after_success:
   - Rscript -e 'library(covr); codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
  