language: r
warnings_are_errors: true
sudo: false
cache: packages


matrix:
  include:
    - os: linux
      dist: trusty
      env: R_CODECOV=true
      r: oldrel
    - os: linux
      dist: trusty
      env: R_CODECOV=true
      r: release
    - os: linux
      dist: trusty
      env: R_CODECOV=true
      r: devel

cran: https://cran.rstudio.com/
r_packages: 
   - covr
   
after_success:
   - Rscript -e 'library(covr); codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
  
